logging:
  file:
    encoding: UTF-8


spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_URL}/${DB_NAME}?autoReconnect=true&setTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
    sql:
      init:
        mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

jwt:
    access-token-expiration: 7200000 # 2 hours
    refresh-token-expiration: 1209600000 # 14 days
    secret:
      key: ${JWT_SECRET}
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true