logging:
  file:
    encoding: UTF-8

# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info # 보안을 위해 health와 info만 공개
  endpoint:
    health:
      show-details: always # actuator/health 에 디테일 정보 반환

aes:
    key: ${AES_KEY}


spring:
  profiles:
    active: local
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_URL}/${DB_NAME}?autoReconnect=true&setTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
    sql:
      init:
        mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

jwt:
    access-token-expiration: 7200000 # 2 hours
    refresh-token-expiration: 1209600000 # 14 days
    secret:
      key: ${JWT_SECRET}
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

football-api:
  base-url: https://v3.football.api-sports.io
  key: ${FOOTBALL_API_KEY}

# SpringDoc OpenAPI 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: honajun.football_community
